<?php
global $current_user;
 date_default_timezone_set('Australia/Melbourne');
$vardefs_array = array(
    "quote_main_tank_water" => array(
        "name" => "quote_main_tank_water",
        "display_label" => "On Mains Water or Tank Water",
        "type" => "select",
        "list_array" => array(
            "",
            "Mains Water",
            "Tank Water",
            "Mains / Tank"
        ) ,
        "parent" => "",
    ),
    "quote_number_sanden" => array(
        "name" => "quote_number_sanden",
        "display_label" => "Number Sanden's",
        "type" => "select",
        "list_array" => array(
            "",
            "1",
            "2"
        ) ,
        "parent" => "",
    ),
    "quote_tank_size" => array(
        "name" => "quote_tank_size",
        "display_label" => "Tank Size",
        "type" => "select",
        "list_array" => array(
            "",
            "Sanden 315FQS",
            "Sanden 300FQS",
            "Sanden 250FQS",
            "Sanden 160FQS",
            "Sanden 315FQV",
        ) ,
        "parent" => "",
    ),
    "quote_plumbing_installation_by_pure" => array(
        "name" => "quote_plumbing_installation_by_pure",
        "display_label" => "Plumbing Installation by PureElectric team",
        "type" => "select",
        "list_array" => array(
            "",
            "Yes",
            "No",
        ) ,
        "parent" => "",
    ),
    "quote_electrical_installation_by_pure" => array(
        "name" => "quote_electrical_installation_by_pure",
        "display_label" => "Electrical Installation by PureElectric team",
        "type" => "select",
        "list_array" => array(
            "",
            "Yes",
            "No",
        ) ,
        "parent" => "",
    ),
    "quote_quick_connection_kit" => array(
        "name" => "quote_quick_connection_kit",
        "display_label" => "Plumbing Quick Connection Kit",
        "type" => "select",
        "list_array" => array(
            "",
            "15mm Quick Connection Kit (QIK15)",
            "20mm Quick Connection Kit (QIK25)",
            "No Quick Connection Kit"
        ) ,
        "parent" => "",
    ),
    "quote_provide_stcs" => array(
        "name" => "quote_provide_stcs",
        "display_label" => "Would you like us to provide STCs as an upfront discount on your quote",
        "type" => "select",
        "list_array" => array(
            "",
            "Yes",
            "No",
        ) ,
        "parent" => "",
    ),
    "quote_pickup_site_delivery" => array(
        "name" => "quote_pickup_site_delivery",
        "display_label" => "Pick up or Site Delivery",
        "type" => "select",
        "list_array" => array(
            "",
            "Pick Up",
            "Site Delivery",
        ) ,
        "parent" => "",
    ),
    "quote_choice_type_install" => array(
        "name" => "quote_choice_type_install",
        "display_label" => "Replace an existing Hot Water System (HWS) or do you have no HWS (e.g. new build, renovation)",
        "type" => "select",
        "list_array" => array(
            "",
            "Replace Hot Water System",
            "New Build/Renovation",
        ) ,
        "parent" => "",
    ),
    "quote_replacement_urgent" => array(
        "name" => "quote_replacement_urgent",
        "display_label" => "Is Your Replacement Urgent",
        "type" => "select",
        "list_array" => array(
            "",
            "Yes",
            "No",
        ) ,
        "parent" => "",
    ),
    "quote_choice_type_product" => array(
        "name" => "quote_choice_type_product",
        "display_label" => "Which one are you replacing",
        "type" => "select",
        "list_array" => array(
            "",
            "Gas",
            "Electric",
            "Solar",
            "Wood",
            "LPG",
            "Heatpump",
        ) ,
        "parent" => "",
    ),
    "quote_product_choice_type_gas" => array(
        "name" => "quote_product_choice_type_gas",
        "display_label" => "Gas type",
        "type" => "select",
        "list_array" => array(
            "",
            "Gas Instant",
            "Gas Storage",
        ) ,
        "parent" => "",
    ),
    "quote_gas_connection" => array(
        "name" => "quote_gas_connection",
        "display_label" => "Gas instant electrical connection",
        "type" => "select",
        "list_array" => array(
            "",
            "Plug in to powerpoint",
            "No electrical connection",
        ) ,
        "parent" => "",
    ),
    "quote_product_choice_type_electric" => array(
        "name" => "quote_product_choice_type_electric",
        "display_label" => "Electric type",
        "type" => "select",
        "list_array" => array(
            "",
            "Electric Storage",
            "Gravity Feed",
        ) ,
        "parent" => "",
    ),
    "quote_electric_storage_located" => array(
        "name" => "quote_electric_storage_located",
        "display_label" => "Where is your electric storage located",
        "type" => "select",
        "list_array" => array(
            "",
            "Outside",
            "Inside",
        ) ,
        "parent" => "",
    ),
    "quote_about_outside" => array(
        "name" => "quote_about_outside",
        "display_label" => "About outside",
        "type" => "select",
        "list_array" => array(
            "",
            "On ground adjacent external wall",
            "Under the house",
            "Balcony",
            "Rooftop",
            "On wall bracket",
        ) ,
        "parent" => "",
    ),
    "quote_about_inside" => array(
        "name" => "quote_about_inside",
        "display_label" => "About inside",
        "type" => "select",
        "list_array" => array(
            "",
            "Inside Adjacent Perimeter Wall",
            "Inside Laundry",
            "Inside Cupboard",
        ) ,
        "parent" => "",
    ),
    "quote_product_choice_type_solar" => array(
        "name" => "quote_product_choice_type_solar",
        "display_label" => "Solar type",
        "type" => "select",
        "list_array" => array(
            "",
            "Electric Storage",
            "Ground Tank",
        ) ,
        "parent" => "",
    ),
    "quote_solar_boosted" => array(
        "name" => "quote_solar_boosted",
        "display_label" => "How is it boosted",
        "type" => "select",
        "list_array" => array(
            "",
            "Electric Boost",
            "Gas Boost",
            "Ground Instant Gas Boost",
            "Wood Boost",
        ) ,
        "parent" => "",
    ),
    "quote_product_choice_type_wood" => array(
        "name" => "quote_product_choice_type_wood",
        "display_label" => "Wood type",
        "type" => "select",
        "list_array" => array(
            "",
            "Wetback Stove",
            "Mains Pressure System",
            "Low Pressure System",
        ) ,
        "parent" => "",
    ),
    "quote_product_choice_type_lpg" => array(
        "name" => "quote_product_choice_type_lpg",
        "display_label" => "LPG type",
        "type" => "select",
        "list_array" => array(
            "",
            "Wetback Stove",
            "Mains Pressure System",
            "Low Pressure System",
        ) ,
        "parent" => "",
    ),
    "quote_new_place_choice" => array(
        "name" => "quote_new_place_choice",
        "display_label" => "New Sanden HWS Install Location",
        "type" => "select",
        "list_array" => array(
            "",
            "Same as existing HWS",
            "New HWS relocation",
        ) ,
        "parent" => "",
    ),
    "quote_existing_install_location" => array(
        "name" => "quote_existing_install_location",
        "display_label" => "Existing system install location",
        "type" => "select",
        "list_array" => array(
            "",
            "External wall house",
            "Inside perimeter wall",
            "Laundry",
            "Ceiling Cavity",
            "Internal cupboard",
            "Garage",
            "Shed",
            "Sub floor open air",
            "Balcony",
            "Basement enclosed",
            "Utilities Room",
            "Rooftop"
        ) ,
        "parent" => "",
    ),
    "quote_install_location_access" => array(
        "name" => "quote_install_location_access",
        "display_label" => "Install Location Access",
        "type" => "select",
        "list_array" => array(
            "",
            "Easy Access",
            "Unpaved Path",
            "Across grassed are",
            "Through Building",
        ) ,
        "parent" => "",
    ),
    "quote_stair_access" => array(
        "name" => "quote_stair_access",
        "display_label" => "Stairs",
        "type" => "select",
        "list_array" => array(
            "",
            "No Stairs",
            "Few Steps - Trolley Ok",
            "Stairs - Trolley Ok",
            "Stairs No Trolley Access",
            "Few Steps No Trolley Access",
            "Internal Stairs -No Trolley",
        ) ,
        "parent" => "",
    ),
    "quote_alectrical_already" => array(
        "name" => "quote_alectrical_already",
        "display_label" => "Electrical Already RCD Protected",
        "type" => "select",
        "list_array" => array(
            "",
            "Yes",
            "No",
        ) ,
        "parent" => "",
    ),
    "quote_hot_cold_connections" => array(
        "name" => "quote_hot_cold_connections",
        "display_label" => "Hot and Cold Connections presented, externally located, single storey, paved area",
        "type" => "select",
        "list_array" => array(
            "",
            "Yes",
            "No",
        ) ,
        "parent" => "",
    ),
    "quote_located_within" => array(
        "name" => "quote_located_within",
        "display_label" => "New Sanden tank to be located within 2m of hot and cold connections",
        "type" => "select",
        "list_array" => array(
            "",
            "Yes",
            "No",
        ) ,
        "parent" => "",
    ),
    "quote_additional_untempered" => array(
        "name" => "quote_additional_untempered",
        "display_label" => "Confirm you don't have an untempered hot water line (> 50 deg) - majority of houses answer YES to this question",
        "type" => "select",
        "list_array" => array(
            "",
            "Yes",
            "No",
        ) ,
        "parent" => "",
    ),
    "quote_concrete_slab" => array(
        "name" => "quote_concrete_slab",
        "display_label" => "Would you like us to bring a 600x600 concrete slab for the tank",
        "type" => "select",
        "list_array" => array(
            "",
            "Yes",
            "No",
        ) ,
        "parent" => "",
    ),
    "quote_concrete_pavers" => array(
        "name" => "quote_concrete_pavers",
        "display_label" => "Would you like us to bring 2x 450x450 concrete pavers for the Heat Pump",
        "type" => "select",
        "list_array" => array(
            "",
            "Yes",
            "No",
        ) ,
        "parent" => "",
    ),
    "quote_hot_water_rebate" => array(
        "name" => "quote_hot_water_rebate",
        "display_label" => "Solar Vic Solar Hot Water Rebate - Do you qualify?",
        "type" => "select",
        "list_array" => array(
            "",
            "Yes",
            "No",
        ) ,
        "parent" => "",
    )
);