<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */
$relationships = array (
  'aos_invoices_po_purchase_order_1' => 
  array (
    'id' => '7496d074-780f-23f4-fe21-5f83d8c13d1f',
    'relationship_name' => 'aos_invoices_po_purchase_order_1',
    'lhs_module' => 'AOS_Invoices',
    'lhs_table' => 'aos_invoices',
    'lhs_key' => 'id',
    'rhs_module' => 'PO_purchase_order',
    'rhs_table' => 'po_purchase_order',
    'rhs_key' => 'id',
    'join_table' => 'aos_invoices_po_purchase_order_1_c',
    'join_key_lhs' => 'aos_invoices_po_purchase_order_1aos_invoices_ida',
    'join_key_rhs' => 'aos_invoices_po_purchase_order_1po_purchase_order_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'aos_quotes_po_purchase_order_1' => 
  array (
    'id' => '7a552243-4480-7e8f-17bc-5f83d84968af',
    'relationship_name' => 'aos_quotes_po_purchase_order_1',
    'lhs_module' => 'AOS_Quotes',
    'lhs_table' => 'aos_quotes',
    'lhs_key' => 'id',
    'rhs_module' => 'PO_purchase_order',
    'rhs_table' => 'po_purchase_order',
    'rhs_key' => 'id',
    'join_table' => 'aos_quotes_po_purchase_order_1_c',
    'join_key_lhs' => 'aos_quotes_po_purchase_order_1aos_quotes_ida',
    'join_key_rhs' => 'aos_quotes_po_purchase_order_1po_purchase_order_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'po_purchase_order_pe_warehouse_log_1' => 
  array (
    'id' => '95d24aef-c301-92c0-5724-5f83d855494a',
    'relationship_name' => 'po_purchase_order_pe_warehouse_log_1',
    'lhs_module' => 'PO_purchase_order',
    'lhs_table' => 'po_purchase_order',
    'lhs_key' => 'id',
    'rhs_module' => 'pe_warehouse_log',
    'rhs_table' => 'pe_warehouse_log',
    'rhs_key' => 'id',
    'join_table' => 'po_purchase_order_pe_warehouse_log_1_c',
    'join_key_lhs' => 'po_purchase_order_pe_warehouse_log_1po_purchase_order_ida',
    'join_key_rhs' => 'po_purchase_order_pe_warehouse_log_1pe_warehouse_log_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'po_purchase_order_aos_products_quotes_1' => 
  array (
    'id' => '986564a5-91d8-b6ae-a242-5f83d83a473a',
    'relationship_name' => 'po_purchase_order_aos_products_quotes_1',
    'lhs_module' => 'PO_purchase_order',
    'lhs_table' => 'po_purchase_order',
    'lhs_key' => 'id',
    'rhs_module' => 'AOS_Products_Quotes',
    'rhs_table' => 'aos_products_quotes',
    'rhs_key' => 'id',
    'join_table' => 'po_purchase_order_aos_products_quotes_1_c',
    'join_key_lhs' => 'po_purchase_order_aos_products_quotes_1po_purchase_order_ida',
    'join_key_rhs' => 'po_purchase_order_aos_products_quotes_1aos_products_quotes_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'po_purchase_order_pe_internal_note_1' => 
  array (
    'id' => '99d9ad72-6313-0c9e-a4bf-5f83d860e731',
    'relationship_name' => 'po_purchase_order_pe_internal_note_1',
    'lhs_module' => 'PO_purchase_order',
    'lhs_table' => 'po_purchase_order',
    'lhs_key' => 'id',
    'rhs_module' => 'pe_internal_note',
    'rhs_table' => 'pe_internal_note',
    'rhs_key' => 'id',
    'join_table' => 'po_purchase_order_pe_internal_note_1_c',
    'join_key_lhs' => 'po_purchase_order_pe_internal_note_1po_purchase_order_ida',
    'join_key_rhs' => 'po_purchase_order_pe_internal_note_1pe_internal_note_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'po_purchase_order_emails_1' => 
  array (
    'id' => '9b337fee-8c7e-0e7b-611f-5f83d8c693d9',
    'relationship_name' => 'po_purchase_order_emails_1',
    'lhs_module' => 'PO_purchase_order',
    'lhs_table' => 'po_purchase_order',
    'lhs_key' => 'id',
    'rhs_module' => 'Emails',
    'rhs_table' => 'emails',
    'rhs_key' => 'id',
    'join_table' => 'po_purchase_order_emails_1_c',
    'join_key_lhs' => 'po_purchase_order_emails_1po_purchase_order_ida',
    'join_key_rhs' => 'po_purchase_order_emails_1emails_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForQueues',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'account_po_purchase_order' => 
  array (
    'id' => 'd5c80932-1172-7158-da79-5f83d8d1bb3e',
    'relationship_name' => 'account_po_purchase_order',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'PO_purchase_order',
    'rhs_table' => 'po_purchase_order',
    'rhs_key' => 'billing_account_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'po_purchase_order_modified_user' => 
  array (
    'id' => 'dad93c94-89b1-b701-0586-5f83d83c5f53',
    'relationship_name' => 'po_purchase_order_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'PO_purchase_order',
    'rhs_table' => 'po_purchase_order',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'po_purchase_order_created_by' => 
  array (
    'id' => 'dc4a8e5c-9641-c71c-79a9-5f83d8786819',
    'relationship_name' => 'po_purchase_order_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'PO_purchase_order',
    'rhs_table' => 'po_purchase_order',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'po_purchase_order_assigned_user' => 
  array (
    'id' => 'dd9f6bf0-b940-623c-dfdf-5f83d868a233',
    'relationship_name' => 'po_purchase_order_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'PO_purchase_order',
    'rhs_table' => 'po_purchase_order',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'securitygroups_po_purchase_order' => 
  array (
    'id' => 'def3479c-439f-0020-da21-5f83d8b53e67',
    'relationship_name' => 'securitygroups_po_purchase_order',
    'lhs_module' => 'SecurityGroups',
    'lhs_table' => 'securitygroups',
    'lhs_key' => 'id',
    'rhs_module' => 'PO_purchase_order',
    'rhs_table' => 'po_purchase_order',
    'rhs_key' => 'id',
    'join_table' => 'securitygroups_records',
    'join_key_lhs' => 'securitygroup_id',
    'join_key_rhs' => 'record_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'module',
    'relationship_role_column_value' => 'PO_purchase_order',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'po_purchase_order_emails_2' => 
  array (
    'rhs_label' => 'Emails',
    'lhs_label' => 'Purchase Order',
    'lhs_subpanel' => 'default',
    'rhs_subpanel' => 'ForQueues',
    'lhs_module' => 'PO_purchase_order',
    'rhs_module' => 'Emails',
    'relationship_type' => 'many-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'po_purchase_order_emails_2',
  ),
);